from base import *
E=[('Pflegeprozess','Der 6-stufige Regelkreis nach Fiechter &amp; Meier',[('1','Informationen sammeln – Anamnese, Assessment'),('2','Probleme und Ressourcen erkennen'),('3','Pflegeziele festlegen – realistisch, überprüfbar'),('4','Maßnahmen planen – wer, was, wann, wie oft'),('5','Maßnahmen durchführen'),('6','Evaluation – Ziel erreicht? Plan anpassen')],'Ressourcen immer ausdrücklich dokumentieren.'),
('PESR','Pflegeproblem richtig formulieren',[('P','Problem – das pflegerische Problem benennen'),('E','Einflussfaktoren – Ursache („bedingt durch")'),('S','Symptome – woran erkennbar („zeigt sich durch")'),('R','Ressourcen – was kann der Mensch noch selbst?')],'Problem + Ursache + Symptom + Ressource.'),
('SMART','Pflegeziele, die im Examen zählen',[('S','Spezifisch – konkret und eindeutig'),('M','Messbar – woran erkennt man den Erfolg?'),('A','Attraktiv / akzeptiert – vom Patienten mitgetragen'),('R','Realistisch – mit den Ressourcen erreichbar'),('T','Terminiert – mit klarem Zeitrahmen')],'Ein Ziel beschreibt den Zustand des Patienten, nicht deine Tätigkeit.'),
('12 ATL','Aktivitäten des täglichen Lebens nach Liliane Juchli',[('Körper','Wach sein &amp; schlafen · Sich bewegen · Sich waschen &amp; kleiden · Essen &amp; trinken · Ausscheiden'),('Vital','Körpertemperatur regulieren · Atmen'),('Sicherheit','Sich sicher fühlen und verhalten · Raum &amp; Zeit gestalten'),('Sozial','Kommunizieren · Kind, Frau, Mann sein · Sinn finden')],'ATL sind die Grundlage jeder strukturierten Pflegeplanung.'),
('13 AEDL','Das Modell von Monika Krohwinkel',[('Name','Aktivitäten und existenzielle Erfahrungen des Lebens'),('Kern','Erweitert die ATL um soziale Beziehungen und existenzielle Erfahrungen'),('Beispiel','„Mit existenziellen Erfahrungen des Lebens umgehen können"'),('Ziel','Ganzheitliche, fördernde Prozesspflege')],'AEDL betont das Existenzielle, ATL eher das Funktionelle.'),
('10-R-Regel','Sichere Medikamentengabe',[('1–5','Richtiger Patient · Medikament · Dosierung · Applikationsform · Zeitpunkt'),('6–10','Richtige Dokumentation · Wirkung · Aufklärung · Haltbarkeit · Entsorgung')],'Im Zweifel immer nachfragen – nie raten.'),
('Prophylaxen','Die Klassiker der Grundpflege',[('Dekubitus','Bewegungsförderung, Mikrolagerung, Hautpflege, Braden-Skala'),('Pneumonie','Atemübungen, Mobilisation, ausreichend trinken'),('Thrombose','MTS, Bewegung, Hochlagern, ggf. Heparin nach Anordnung'),('Sturz','Umgebung sichern, Hilfsmittel, Sturzrisiko einschätzen'),('Kontraktur','Lagern in Funktionsstellung, Bewegungsübungen')],'Jede Prophylaxe braucht eine Indikation und Dokumentation.'),
('Dekubitus','Die 4 Feinde der Haut',[('Druck','Anhaltender Auflagedruck über Knochenvorsprüngen'),('Zeit','Je länger der Druck, desto höher das Risiko'),('Reibung','Scherkräfte beim Bewegen und Lagern'),('Feuchtigkeit','Mazeration durch Schweiß, Urin, Wundsekret')],'Risiko einschätzen mit Braden- oder Norton-Skala.'),
('SBAR','Strukturierte Übergabe',[('S','Situation – Wer? Was ist das aktuelle Problem?'),('B','Background – Vorgeschichte, Diagnosen'),('A','Assessment – deine pflegerische Einschätzung'),('R','Recommendation – konkreter Vorschlag oder Bitte')],'Klare Übergabe = Patientensicherheit.'),
('SOAP','Klare Pflegedokumentation',[('S','Subjektiv – Angaben und Empfinden des Patienten'),('O','Objektiv – Messwerte, Beobachtungen, Befunde'),('A','Assessment – fachliche Beurteilung'),('P','Plan – weiteres pflegerisches Vorgehen')],'Sachlich, wertfrei und nachvollziehbar dokumentieren.'),
('ABCDE','Strukturierte Notfalleinschätzung',[('A','Airway – Atemweg frei?'),('B','Breathing – Frequenz, Tiefe, SpO<sub>2</sub>'),('C','Circulation – Puls, Blutdruck, Rekapillarisierung'),('D','Disability – Bewusstsein (GCS), Pupillen, Blutzucker'),('E','Exposure – Entkleiden, Wärmeerhalt, Body-Check')],'Erst stabilisieren, dann weiter.'),
('5 Momente','WHO-Händedesinfektion',[('1','Vor Patientenkontakt'),('2','Vor aseptischer Tätigkeit'),('3','Nach Kontakt mit Körperflüssigkeiten'),('4','Nach Patientenkontakt'),('5','Nach Kontakt mit der Patientenumgebung')],'Handschuhe ersetzen die Händedesinfektion nicht.')]
X=""".eg{display:grid;grid-template-columns:1fr 1fr;gap:4mm}.eb{border:0.8pt solid #e2e8f0;border-top:2.4pt solid #14b8a6;border-radius:3mm;padding:3.2mm 4mm;break-inside:avoid}
.eb .h{display:flex;align-items:baseline;gap:2mm}.eb .h b{font:800 12.5pt M;color:#0b1a35}.eb .h span{font:800 8pt M;color:#14b8a6}
.eb .s{font:600 8pt M;color:#64748b;margin:.5mm 0 2mm}.eb table{width:100%;border-collapse:collapse;font-size:8.8pt}.eb td{padding:.9mm 0;vertical-align:top;border-top:0.4pt solid #f1f5f9}
.eb td:first-child{width:21mm;padding-right:2mm;font:800 7.8pt M;color:#0284c7}.eb .m{margin-top:1.8mm;background:#f0fdfa;border-radius:1.5mm;padding:1.4mm 2.4mm;font-size:8.3pt;color:#134e4a}.eb .m b{font-weight:700}"""
def box(i,t,s,rows,m): return f'<div class="eb"><div class="h"><span>{i:02d}</span><b>{t}</b></div><div class="s">{s}</div><table>'+''.join(f'<tr><td>{a}</td><td>{b}</td></tr>' for a,b in rows)+f'</table><div class="m"><b>Merke:</b> {m}</div></div>'
b=cover('Gratis-Lernhilfe · Zum Ausdrucken','12 Eselsbrücken<br>fürs Pflegeexamen','Pflegeprozess, PESR, SMART, ATL, AEDL und mehr – die wichtigsten Pflege-Schemata kompakt auf den Punkt gebracht. Ausdrucken und an den Lernplatz hängen.',
 ['Pflegeplanung','Pflegeziele','ATL / AEDL','Notfall','Hygiene'],[('12','Eselsbrücken'),('A4','druckfertig'),('100%','kostenlos')],
 'Lernhilfe für Ausbildung und Prüfung, ersetzt kein Lehrbuch. Es gelten deine Lehrinhalte und die Standards deiner Einrichtung.',
 toc=[e[0] for e in E[:8]]+['… und 4 weitere'])
b+='<h2>Die 12 Eselsbrücken</h2><p class="lead">Jede Karte: Schema, Erklärung, Merksatz.</p><div class="eg">'+''.join(box(i+1,*e) for i,e in enumerate(E))+'</div>'+endbox()
build('/mnt/user-data/outputs/PLAN-NRW_12-Eselsbruecken.pdf','12 Eselsbrücken fürs Pflegeexamen',b,X)
